#!/usr/bin/env bash
# Set up Grafana Alloy on an external VM to ship systemd journal logs
# to the homelab Loki (job="systemd-journal").
#
# Docker hosts: container logs are handled by the alloy service in the
# docker-compose.yml next to this script — run this script too if you
# also want the host's journal.
#
# Usage:
#   sudo ./setup-alloy.sh [host-label]
#
#   host-label   label attached to every log line (default: hostname)
#
# Env overrides:
#   LOKI_URL     push endpoint (default: http://loki.kube.local.tnndev.com/loki/api/v1/push)
#
# Supports Debian/Ubuntu (apt). For other distros install Alloy manually
# (https://grafana.com/docs/alloy/latest/set-up/install/) and reuse the
# generated /etc/alloy/config.alloy from this script.
set -euo pipefail

LOKI_URL="${LOKI_URL:-http://loki.kube.local.tnndev.com/loki/api/v1/push}"
HOST_LABEL="${1:-$(hostname)}"
CONFIG_FILE="/etc/alloy/config.alloy"

if [[ $EUID -ne 0 ]]; then
  echo "Run as root: sudo $0 [host-label]" >&2
  exit 1
fi

# ---------------------------------------------------------------- install
if ! command -v alloy >/dev/null 2>&1; then
  echo ">> Installing Grafana Alloy (apt)..."
  if ! command -v apt-get >/dev/null 2>&1; then
    echo "apt-get not found. Install Alloy manually, then re-run this script to generate config." >&2
    exit 1
  fi
  apt-get install -y gpg wget >/dev/null
  mkdir -p /etc/apt/keyrings
  wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor >/etc/apt/keyrings/grafana.gpg
  echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" \
    >/etc/apt/sources.list.d/grafana.list
  apt-get update -qq
  apt-get install -y alloy
else
  echo ">> Alloy already installed, skipping install."
fi

# ------------------------------------------------------------ permissions
# journal access
usermod -aG systemd-journal alloy 2>/dev/null || true

# ----------------------------------------------------------------- config
echo ">> Writing ${CONFIG_FILE} (host=${HOST_LABEL})"
mkdir -p "$(dirname "$CONFIG_FILE")"

cat >"$CONFIG_FILE" <<EOF
// Generated by setup-alloy.sh — ships systemd journal logs to the homelab Loki.

loki.write "homelab" {
  endpoint {
    url = "${LOKI_URL}"
  }
  external_labels = {
    host = "${HOST_LABEL}",
  }
}

// targets = [] is the documented pattern: this component only supplies
// relabel rules to loki.source.journal below.
discovery.relabel "journal" {
  targets = []
  rule {
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }
}

loki.source.journal "system" {
  relabel_rules = discovery.relabel.journal.rules
  forward_to    = [loki.write.homelab.receiver]
  labels        = { job = "systemd-journal" }
}
EOF

# ------------------------------------------------------------------ start
echo ">> Validating config..."
alloy fmt "$CONFIG_FILE" >/dev/null

echo ">> Enabling and (re)starting alloy service..."
systemctl enable alloy >/dev/null
systemctl restart alloy
sleep 2
systemctl --no-pager --quiet is-active alloy && echo ">> alloy is running."

cat <<EOF

Done. Journal logs from this machine now push to:
  ${LOKI_URL}
Query in Grafana with: {host="${HOST_LABEL}"}

For metrics, also run node_exporter / cadvisor (see docker-compose.yml in
this folder) and register this machine's IP in
infrastructure/configs/monitoring-external-scrape.yaml.
EOF
