---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db-recovered
  namespace: postgres-authentik
  annotations:
    # Prevent accidental deletion while this is the emergency recovery DB.
    kustomize.toolkit.fluxcd.io/prune: Disabled
spec:
  # Recover only one primary initially.
  instances: 1

  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  primaryUpdateStrategy: unsupervised

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  bootstrap:
    recovery:
      volumeSnapshots:
        storage:
          name: authentik-db-daily-snapshot-20260727020000
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

        walStorage:
          name: authentik-db-daily-snapshot-20260727020000-wal
          kind: VolumeSnapshot
          apiGroup: snapshot.storage.k8s.io

      database: authentik
      owner: authentik
      secret:
        name: authentik-db-app

  storage:
    storageClass: longhorn
    size: 4Gi

  walStorage:
    storageClass: longhorn
    size: 16Gi