---
apiVersion: v1
kind: Namespace
metadata:
  name: infisical-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 24h
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical-secrets-operator
  namespace: infisical-operator-system
spec:
  interval: 1h
  chart:
    spec:
      chart: secrets-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
      interval: 12h
