apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi-snapshot-controller.yaml
  - metallb.yaml
  - longhorn.yaml
  - envoy-gateway.yaml
  - infisical.yaml
  - cloudnative-pg.yaml
