[masters]
k3s-master-1 ansible_host=10.10.30.21
k3s-master-2 ansible_host=10.10.30.22
k3s-master-3 ansible_host=10.10.30.23

[workers]
k3s-worker-1 ansible_host=10.10.30.31
k3s-worker-2 ansible_host=10.10.30.32
k3s-worker-3 ansible_host=10.10.30.33

[k3s_cluster:children]
masters
workers

[k3s_cluster:vars]
# The VIP that kube-vip will manage
k3s_vip=10.10.30.20
# Token shared between all K3s nodes (generate one: openssl rand -hex 32)
k3s_token=512470c385a607382eb6205d72fced9c2a874c4e1aee5e774db52857c7c477c1
# Network interface name (check with: ip addr)
k3s_interface=eth0
