apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hello-word.yaml
  - authentik/authentik-postgres.yaml
  - authentik/authentik-postgres-dump.yaml
  - authentik/authentik.yaml
  - cloudflared/authentik.yaml
  - immich/immich-postgres.yaml
  - alloy.yaml
  - monitoring/authentik-liveness-dashboard.yaml

